#!/usr/bin/env python3
# -*- coding: utf-8 -*-

print("=" * 70)
print("ОБЪЯСНЕНИЕ РЕКОМЕНДАЦИЙ")
print("=" * 70)

print("\n1. УЖЕСТОЧИТЬ ТРЕБОВАНИЯ ДЛЯ EXTENDED TIER")
print("-" * 70)
print("\nСЕЙЧАС В КОДЕ:")
print("  EXTENDED_MIN_DOMINANCE = 3.0")
print("  EXTENDED_MIN_XG_DIFF = 0.1")
print("  EXTENDED_MIN_SOT_DIFF = 0")
print("\nЭто означает:")
print("  - Матч проходит, если dominance >= 3.0 (очень слабый перевес)")
print("  - ИЛИ разница xG >= 0.1 (почти ничего)")
print("  - ИЛИ разница ударов в створ >= 0 (даже если равная!)")
print("\nПРОБЛЕМА:")
print("  Матч с кэфом 1.4 может пройти с dominance всего 3.0")
print("  Это очень рискованно - перевес слишком слабый!")

print("\nРЕКОМЕНДУЕМОЕ ИЗМЕНЕНИЕ:")
print("  EXTENDED_MIN_DOMINANCE = 6.0  # Было 3.0")
print("  EXTENDED_MIN_XG_DIFF = 0.3     # Было 0.1")
print("  EXTENDED_MIN_SOT_DIFF = 1      # Было 0")
print("\nЭто означает:")
print("  - Матч проходит, если dominance >= 6.0 (более сильный перевес)")
print("  - И разница xG >= 0.3 (статистически значимо)")
print("  - И разница ударов в створ >= 1 (реальное преимущество)")
print("\nРЕЗУЛЬТАТ:")
print("  Меньше матчей, но более надежных")
print("  Процент выигрышей останется высоким")

print("\n" + "=" * 70)
print("2. УЧИТЫВАТЬ ВРЕМЯ МАТЧА")
print("-" * 70)
print("\nСЕЙЧАС В КОДЕ:")
print("  Система НЕ учитывает, на какой минуте матч")
print("  Матч 1:0 на 20-й минуте = матч 1:0 на 80-й минуте")
print("\nПРОБЛЕМА:")
print("  Матч на 20-й минуте с перевесом 1:0 - это НЕ надежно!")
print("  Еще 70 минут игры - все может измениться")
print("  Матч на 80-й минуте с перевесом 1:0 - это надежнее")
print("  Осталось 10 минут - мало времени для отыгрыша")

print("\nРЕКОМЕНДУЕМОЕ ИЗМЕНЕНИЕ:")
print("  Добавить проверку времени матча:")
print("\n  if minute < 30:")
print("      # Ранний матч - нужен БОЛЬШОЙ перевес")
print("      required_dominance = 8.0")
print("  elif minute < 60:")
print("      # Средний матч - стандартные требования")
print("      required_dominance = 6.0")
print("  else:")
print("      # Поздний матч - можно немного снизить")
print("      required_dominance = 5.0")
print("\nРЕЗУЛЬТАТ:")
print("  Ранние матчи с небольшим перевесом не проходят")
print("  Поздние матчи с перевесом проходят чаще")
print("  Качество отбора повышается")

print("\n" + "=" * 70)
print("3. УЛУЧШИТЬ ФОРМУЛУ DOMINANCE_SCORE")
print("-" * 70)
print("\nСЕЙЧАС В КОДЕ:")
print("  dominance = xG_diff * 3")
print("           + shots_on_target_diff * 2")
print("           + shots_total_diff * 0.5")
print("           + possession_diff * 0.2")
print("\nПРОБЛЕМА:")
print("  Не учитывается время матча")
print("  Не учитывается текущий счет")
print("  Владение имеет слишком маленький вес")

print("\nРЕКОМЕНДУЕМОЕ ИЗМЕНЕНИЕ:")
print("  # Учитываем время матча")
print("  time_factor = minute / 90.0  # 0.22 для 20-й минуты, 0.89 для 80-й")
print("  ")
print("  # Учитываем текущий счет")
print("  score_factor = score_diff * 2  # 1:0 = 2, 2:0 = 4")
print("  ")
print("  # Увеличиваем вес владения")
print("  dominance = xG_diff * 3")
print("           + shots_on_target_diff * 2")
print("           + shots_total_diff * 0.5")
print("           + possession_diff * 0.5  # Было 0.2")
print("           + score_factor * time_factor  # Учитываем счет и время")
print("\nРЕЗУЛЬТАТ:")
print("  Матч 1:0 на 80-й минуте получит больше dominance")
print("  Матч 1:0 на 20-й минуте получит меньше dominance")
print("  Формула более точно отражает реальную ситуацию")

print("\n" + "=" * 70)
print("ПРИМЕР:")
print("-" * 70)
print("\nМатч А: 1:0 на 20-й минуте, xG 0.5-0.3, удары 3-2")
print("  СЕЙЧАС: dominance = 3.0 (может пройти)")
print("  С УЧЕТОМ ВРЕМЕНИ: dominance = 1.5 (НЕ пройдет - слишком рано)")
print("\nМатч Б: 1:0 на 80-й минуте, xG 0.5-0.3, удары 3-2")
print("  СЕЙЧАС: dominance = 3.0 (может пройти)")
print("  С УЧЕТОМ ВРЕМЕНИ: dominance = 5.5 (пройдет - надежно!)")
print("\n" + "=" * 70)

